############################################################
#   _____                        _        ____        _    #
#  / ____|                      | |      |  _ \      | |   #
# | |     __ _ ___  ___ __ _  __| | ___  | |_) | ___ | |_  #
# | |    / _` / __|/ __/ _` |/ _` |/ _ \ |  _ < / _ \| __| #
# | |___| (_| \__ \ (_| (_| | (_| |  __/ | |_) | (_) | |_  #
#  \_____\__,_|___/\___\__,_|\__,_|\___| |____/ \___/ \__| #
#                                                          #
# This is the config for Cascade Bot. Each field is        #
# commented with its usage.                                #
#                                                          #
# Fields marked with "# REQUIRED" need to be entered for   #
# the bot to start. Default values are filled out in the   #
# relevant fields                                          #
#                                                          #
# If you have any questions ask the Cascade Bot Dev team!  #
############################################################

# Whether to output DEBUG messages to STDOUT
debug: false

# The Sentry DSN to use for reporting errors
sentry_dsn: ''

# REQUIRED
# The token and client ID for the bot, kinda self explanatory...
bot:
  id: -1
  token: ''

# REQUIRED
# All should be prettyyy self explanatory...
# If you have a connection string, only use that field.
# If not, comment out the connection string and fill out the other fields
database:
  # connection_string: 'connection string here'
  username: ''
  password: ''
  database: ''
  hosts:
    - ''
  ssl: false

# The number of shard to have. Leave at -1 if you don't know what you're doing!
shard_num: -1

# The ID of the server to use for role checking and various other things
official_server: 488394590458478602

# Whether GSON should produce minified JSON or not.
# Recommended not to enable this unless you are debugging.
pretty_json: false

# The default prefix that the bot should use.
default_prefix: ';'

# Config the security levels for the bot
# Each security level can have role IDs and user IDs assigned to it
# The available security levels are: staff, developer and owner
# If a user has a security level, they will be able to access all security levels below it
# i.e. USER has OWNER level, can operate at level STAFF and DEVELOPER also
# IDs can be assigned in an array [id, id] or on their own if there is only one
security_levels:
  owner:
  developer:
  staff:


# Global emotes the bot can use to display various information
global_emotes:
  online:
  offline:
  dnd:
  idle:
  server_owner:
  nitro:
  muted:
  deafened:


# The haste server to use for "hasting" messages.
# Server is the place to submit requests, link is the prefix before the returned code.
haste:
  server: 'https://hastebin.com/documents'
  link: 'https://hastebin.com/'

web:
  # The secret to use when authenticating with the site/wrapper
  secret_key: